# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Pedro Sartori Locatelli
title: PhD Candidate in Electrical Engineering 
email: pedrosartloc@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: pedroslo
linkedin_username: pedro-sartori-locatelli
orcid_username: 0000-0003-3318-0194

# Additional icon links
additional_links:
  - title: Portuguese CV
    icon: fas fa-globe
    url: shorturl.at/moxT5

# About Section
about_profile_image: images/perfil.jpg
about_content: |
  Hi! I’m currently a PhD candidate in Electrical and Computer Engineering at Dalhousie University, Canada. I received my M.Sc. degree in Electrical Engineering (Microelectronics) at the Federal University of Minas Gerais (UFMG), Brazil, acting as a Visiting Graduate Researcher for one semester at Dalhousie University, Canada. I received my B.Sc. in Electrical Engineering from the Federal Center for Technological Education of Minas Gerais (CEFET/MG) in 2020, where I worked as an undergraduate researcher on IC design and image sensors. I also have some teaching experience, having been both undergraduate and graduate teaching assistant.

content:
  - title: Education
    layout: list
    content:
      - layout: left
        title: Dalhousie University
        caption: 2021 - Present
        sub_title: PhD Electrical and Computer Engineering
        description: |
          - **Thesis Title**: Fully Integrated Nose-on-a-Chip System;
          - **Supervisor**: Dr. Kamal El-Sankary;
          - **Co-supervisor**: Dr. Michael S. Freund;
          - **Area of Study**: Microelectronics, IC design, Machine olfaction;
          - **Awards and Scholarships**: Killam Predoctoral Scholarship (Level 2 - Doctoral), Exxon Mobil Canada Ltd. Post-Graduate Scholarship;
          
      - layout: left
        title: Federal University of Minas Gerais
        caption: 2021 - 2023
        sub_title: MSc Electrical Engineering - Microelectronics
        description: |
          - **Thesis Title**: Design of a Time Domain Multiply Accumulate Unit in 180nm CMOS Technology;
          - **Supervisor**: Dr. Dalton Martini Colombo;
          - **Co-supervisor**: Dr. Kamal El-Sankary;
          - **Area of Study**: Microelectronics, IC design;
          - **Awards**: CAPES scholarship holder;
          - **GPA**: 99/100;
          
      - layout: left
        title: Federal Center for Technological Education of Minas Gerais
        caption: 2015 - 2020
        sub_title: BSc Electrical Engineering
        description: |
          - **Thesis Title**: Design of a Current Mode Active Pixel Array for CMOS Image Sensors;
          - **Undergraduate Researcher**: Design and implementation of a library of Integrated Circuits, for didactic and research purposes;
          - **Undergraduate Teaching Assistant**: Assisted the teacher and students in Electrical Power Systems classes; assessment of activities and tests; solved students doubts and assisted in problem resolution; gave complementary lectures;
          - **GPA**: 85.95/100;

  - title: Publications
    layout: list
    content:
      - layout: top-middle
        title: Journal Papers
        description: |
          **[1]** P. Sartori Locatelli, S. Ait Fares, D. Martini Colombo, K. El-Sankary and M. S. Freund, "Multi-Task Spiking Neural Network for Simultaneous Vapor Recognition and Concentration Estimation," in IEEE Access, vol. 13, pp. 29847-29863, 2025, doi: 10.1109/ACCESS.2025.3541408.

          **[2]** P. S. Locatelli, D. M. Colombo and K. El-Sankary, "Time-Domain Multiply–Accumulate Unit," in IEEE Transactions on Very Large Scale Integration (VLSI) Systems, vol. 31, no. 6, pp. 762-775, June 2023, doi: 10.1109/TVLSI.2023.3266743.
          
          **[3]** CARDOSO, D. S.; LOCATELLI, P. S.; RAMALHO, W.; ASGARY, N., "Distributed generation of photovoltaic solar energy: impacts of ANEEL's new regulation proposal on investment attractiveness," Brazilian Journal of Management - ReA UFSM, v.14, p.423-442, 2021.

  - title: Conference Proceedings
    layout: list
    content:
      - layout: top-middle
        title: Papers
        description: |
          **[1]** LOCATELLI, P. S.; CARDOSO, D. S.; RAMALHO, W. "Geração compartilhada de energia fotovoltaica: impactos da proposta de nova regulamentação pela ANEEL na atratividade do investimento." VIII International Symposium on Project Management, Innovation and Sustainability - SINGEP, São Paulo, 2020.

      - layout: top-middle
        title: Presentations
        description: |
          **[1]** LOCATELLI, P. S., "Distributed generation of photovoltaic solar energy: impacts of ANEEL's new regulation proposal on investment attractiveness." VIII SINGEP and 8th CIK Online Conference, 2020.

      - layout: top-middle
        title: Abstracts
        description: |
          **[1]** LOCATELLI, P. S.; SANTOS, P. M.; GOMES, E. A., "Design of an Integrated Circuit library for educational and research purposes." 15th Science and Technology Week, CEFET-MG, 2019.

          **[2]** LOCATELLI, P. S.; SANTOS, P. M., "Integrated Circuit library for educational and research purposes." 14th Science and Technology Week, CEFET-MG, 2018.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: MD Electrical Solutions
        sub_title: Electrical Engineer Intern
        caption: December 2019 - March 2020
        description: |
          Summer internship in Electrical Engineering, focused on Industrial Automation.
          
          Activities included: elaboration of automation projects, system operations descriptions, mapping of inputs and outputs, PLC and Supervisory Systems operation, electrical diagrams elaboration, Ladder programming.

      - layout: left
        title: Faculty of Graduate Studies, Dalhousie University
        sub_title: Graduate Student Mentor
        caption: July 2024 - April 2025
        description: |
          Mentoring graduate students, supporting them academically and personally, leading orientation workshops, information sessions, and panel discussions.

      - layout: left
        title: Dalhousie University
        sub_title: Graduate Teaching Assistant (ECED 3201 - Introduction to Electronics)
        caption: January 2025 - April 2025
        description: |
          Assisted students in understanding fundamental electronics concepts, assessed tests and assignments, supported laboratory sessions.

          
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **EDA tools**: Cadence Virtuoso, LTSpice, Multisim,HSpice, Electric, Synopsis CosmosScope;
      - **Algorithm development environments**: MATLAB, LabVIEW, GNU Octave, Scilab;
      - **Programing languages**: C, Python, Assembly;
      - **Testing and Measurement**: Signal generator, Oscilloscope, Multimeter, Spectrum Analyzer, LabVIEW;
      - **Other tools**: Microsoft Word, Power Point, Excel, LaTeX;

  - title: Awards and Scholarships
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Killam Predoctoral Scholarship (Level 2 - Doctoral)**;
      - **Emerging Leaders in the Americas Program (ELAP)**;
      - **Exxon Mobil Canada Ltd. Post-Graduate Scholarship**;
      - **Ministry of Education in Brazil, CAPES scholarship**;
      - ** ELAP and SICS 2023 Study Tour (Department of Foreign Affairs, Trade and Development Canada & Canadian Bureau for International Education)**;
      


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
