# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Pedro Sartori Locatelli
title: Electrical Engineering Graduate Student
email: pedrosartloc@gmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  pedroslo
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: pedro-sartori-locatelli
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0003-3318-0194

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/perfil.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi! My name is Pedro and  I'm currently pursuing an M.Sc. degree in Electrical Engineering (Microelectronics) at the Federal University of Minas Gearis (UFMG). My research concerns the design of analog and mixed-signal integrated circuits for time-domain applications. I received my B.Sc. in Electrical Engineering from the Federal Center for Technological Education of Minas Gerais (CEFET/MG) in 2020, where I worked as an undergraduated researcher on IC design and image sensors. I also have some teaching experience, having been both undergraduate and graduate teaching assistant. 

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Federal University of Minas Gearis
        caption: 2021 - Present
        sub_title: MSc Electrical Engineering - Microelectronics
        quote: >
          
        description: | # this will include new lines to allow paragraphs
         **• Thesis Title**: Design of a Time Domain Multiply Accumulate Unit in 180nm CMOS Technology
         
         **• Supervisor**: Dr. Dalton Martini Colombo
         **Co-supervisor**: Dr. Kamal El-Sankary
         
         **• Area of Study**: Microelectronics, IC design
      - layout: left
        title: Federal Center for Technological Education of Minas Gerais
        caption: 2015 - 2020
        sub_title: BSc Electrical Engineering 
        description: | # this will include new lines to allow paragraphs
         **• Thesis Title**: Design of a Current Mode Active Pixel Array for CMOS Image Sensors
         
         **• Undergraduate Reasearcher**: Design and implementation of a library of Integrated Circuits, for didactic and research purposes. The focus was to highlight aspects of electronics that cannot be observed in commercial ICs
         
         **• Undergraduate Teaching Assistant**: Assist the teacher and students in Electrical Power Systems classes; Assessment of activities and tests; Solve students doubts and assist in problem resolution; Give complementary lectures for students
         
         **• GPA**: 85.95/100
         
  - title: Publications  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Publications
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          **[1]** CARDOSO, D. S. ; LOCATELLI, P. S. ; RAMALHO, W. ; ASGARY, N. . Distributed generation of photovoltaic solar energy: impacts of ANEEL`s new regulation proposal on investment attractiveness. Brazilian Journal of Management - ReA UFSM, v. 14, p. 423-442, 2021
          
     
  - title: Conference Proceedings  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Papers
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          **[1]** LOCATELLI, P. S. ;CARDOSO, D. S. ; RAMALHO, W. . Geração compartilhada de energia fotovoltaica:: impactos da proposta de nova regulamentação pela ANEEL na atratividade do investimento. In: VIII International Symposium on Project Management, Innovation and Sustainability - SINGEP. São Paulo - SP: Uninove, 2020. v. 1. p. 1-16.
          
      - layout: top-middle
        title: Presentations
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          **[1]** LOCATELLI, P. S. . Distributed generation of photovoltaic solar energy: impacts of ANEEL`s new regulation proposal on investment attractiveness. In: VIII SINGEP and 8th CIK Online Conference

      - layout: top-middle
        title: Abstracts
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          **[1]**  LOCATELLI, P. S.; SANTOS, P. M. ; GOMES, E. A. . Design of an Integrated Circuit library for educational and research purposes. In: 15th Science and Technology Week, Federal Center for Technological Education of Minas Gerais, Belo Horizonte, Brazil. October 2019.
          
          **[2]**  LOCATELLI, P. S.; SANTOS, P. M. . Integrated Circuit library for educational and research purposes. In: 14th Science and Technology Week, Federal Center for Technological Education of Minas Gerais, Belo Horizonte, Brazil. October 2018.


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
